site_name: My Docs
nav:
    - Home: index.md
    - Programming:
        - Language Specific:
          - python: index.md

theme:
  name: material
  palette:
    primary: black
  font:
    code: Roboto Mono

plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

